# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from ....checkout import Checkout as Checkout_1
from ... import CheckoutMandate, MerchantAuthorization


class Ap2(BaseModel):
    """
    AP2 extension data including merchant authorization.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    merchant_authorization: MerchantAuthorization | None = None
    """
    Merchant's signature proving checkout terms are authentic.
    """
    checkout_mandate: CheckoutMandate | None = None
    """
    SD-JWT+kb proving user authorized this checkout.
    """


class Checkout(Checkout_1):
    """
    Checkout extended with AP2 mandate support.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ap2: Ap2 | None = None
    """
    AP2 extension data including merchant authorization.
    """
