# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, RootModel

from ....checkout import Checkout as Checkout_1
from ... import Fulfillment as Fulfillment_1


class Fulfillment(RootModel[Any]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Any


class Checkout(Checkout_1):
    """
    Checkout extended with hierarchical fulfillment.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    fulfillment: Fulfillment_1 | None = None
    """
    Fulfillment details.
    """
