# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, RootModel

from ....checkout import Checkout as Checkout_1
from ....checkout_create_request import (
    CheckoutCreateRequest as CheckoutCreateRequest_1,
)
from ....checkout_update_request import (
    CheckoutUpdateRequest as CheckoutUpdateRequest_1,
)
from ....types import fulfillment_create_request, fulfillment_update_request
from ... import Fulfillment as Fulfillment_1


class Fulfillment(RootModel[Any]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Any


class CheckoutUpdateRequest(CheckoutUpdateRequest_1):
    """
    Checkout extended with hierarchical fulfillment.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    fulfillment: fulfillment_update_request.FulfillmentUpdateRequest | None = (
        None
    )
    """
    Fulfillment details.
    """


class CheckoutCreateRequest(CheckoutCreateRequest_1):
    """
    Checkout extended with hierarchical fulfillment.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    fulfillment: fulfillment_create_request.FulfillmentCreateRequest | None = (
        None
    )
    """
    Fulfillment details.
    """


class Checkout(Checkout_1):
    """
    Checkout extended with hierarchical fulfillment.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    fulfillment: Fulfillment_1 | None = None
    """
    Fulfillment details.
    """
