# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict

from .. import ucp as ucp_1
from .checkout import Checkout as Checkout_1
from .types import attribution as attribution_1
from .types import buyer as buyer_1
from .types import context as context_1
from .types import line_item, link, message
from .types import signals as signals_1
from .types import totals as totals_1


class Cart(BaseModel):
    """
    Shopping cart with estimated pricing before checkout. Lightweight pre-purchase exploration with no payment info or complex status states.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.UcpMetadata
    id: str
    """
    Unique cart identifier.
    """
    line_items: list[line_item.LineItem]
    """
    Cart line items. Same structure as checkout. Full replacement on update.
    """
    context: context_1.Context | None = None
    """
    Buyer signals for localization (country, region, postal_code). Merchant uses for pricing, availability, currency. Falls back to geo-IP if omitted.
    """
    signals: signals_1.Signals | None = None
    attribution: attribution_1.Attribution | None = None
    buyer: buyer_1.Buyer | None = None
    """
    Optional buyer information for personalized estimates.
    """
    currency: str
    """
    ISO 4217 currency code. Determined by merchant based on context or geo-IP.
    """
    totals: totals_1.Totals
    """
    Estimated cost breakdown. May be partial if shipping/tax not yet calculable.
    """
    messages: list[message.Message] | None = None
    """
    Validation messages, warnings, or informational notices.
    """
    links: list[link.Link] | None = None
    """
    Optional merchant links (policies, FAQs).
    """
    continue_url: AnyUrl | None = None
    """
    URL for cart handoff and session recovery. Enables sharing and human-in-the-loop flows.
    """
    expires_at: AwareDatetime | None = None
    """
    Cart expiry timestamp (RFC 3339). Optional.
    """


class Checkout(Checkout_1):
    """
    Checkout extended with cart capability. Adds cart_id to create_checkout for cart-to-checkout conversion.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    cart_id: str | None = None
    """
    Cart ID to convert to checkout. Business MUST use cart contents (line_items, context, buyer) and MUST ignore overlapping fields in checkout payload.
    """
