# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .checkout import Checkout as Checkout_1
from .types import (
    attribution_create_request,
    buyer_create_request,
    context_create_request,
    line_item_create_request,
    signals_create_request,
)


class CartCreateRequest(BaseModel):
    """
    Shopping cart with estimated pricing before checkout. Lightweight pre-purchase exploration with no payment info or complex status states.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    line_items: list[line_item_create_request.LineItemCreateRequest]
    """
    Cart line items. Same structure as checkout. Full replacement on update.
    """
    context: context_create_request.ContextCreateRequest | None = None
    """
    Buyer signals for localization (country, region, postal_code). Merchant uses for pricing, availability, currency. Falls back to geo-IP if omitted.
    """
    signals: signals_create_request.SignalsCreateRequest | None = None
    attribution: attribution_create_request.AttributionCreateRequest | None = (
        None
    )
    buyer: buyer_create_request.BuyerCreateRequest | None = None
    """
    Optional buyer information for personalized estimates.
    """


class Checkout(Checkout_1):
    """
    Checkout extended with cart capability. Adds cart_id to create_checkout for cart-to-checkout conversion.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    cart_id: str | None = None
    """
    Cart ID to convert to checkout. Business MUST use cart contents (line_items, context, buyer) and MUST ignore overlapping fields in checkout payload.
    """
