# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .. import ucp as ucp_1
from .types import attribution as attribution_1
from .types import context as context_1
from .types import message
from .types import pagination as pagination_1
from .types import product, search_filters
from .types import signals as signals_1


class CatalogSearch(BaseModel):
    """
    Product catalog search capability.
    """

    model_config = ConfigDict(
        extra="allow",
    )


class SearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    query: str | None = None
    """
    Free-text search query.
    """
    context: context_1.Context | None = None
    signals: signals_1.Signals | None = None
    attribution: attribution_1.Attribution | None = None
    filters: search_filters.SearchFilters | None = None
    pagination: pagination_1.Request | None = None


class SearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.ResponseCatalogSchema
    products: list[product.Product]
    """
    Products matching the search criteria.
    """
    pagination: pagination_1.Response | None = None
    messages: list[message.Message] | None = None
    """
    Errors, warnings, or informational messages about the search results.
    """
