# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .. import ucp as ucp_1
from .types import attribution as attribution_1
from .types import context as context_1
from .types import (
    detail_option_value,
    input_correlation,
    message,
    search_filters,
    selected_option,
)
from .types import signals as signals_1
from .types.product import Product as Product_1
from .types.variant import Variant


class CatalogLookup(BaseModel):
    """
    Product/variant lookup by identifier. Supports batch retrieval (lookup_catalog) and single-product detail (get_product).
    """

    model_config = ConfigDict(
        extra="allow",
    )


class LookupVariant(Variant):
    """
    Variant with required correlation metadata for lookup responses.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    inputs: list[input_correlation.InputCorrelation] = Field(..., min_length=1)
    """
    Which request identifiers resolved to this variant, and how. Each entry maps a request ID to its match type.
    """


class LookupRequest(BaseModel):
    """
    Request body for catalog lookup.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ids: list[str] = Field(..., min_length=1)
    """
    Identifiers to lookup. Implementations MUST support product ID and variant ID; MAY support secondary identifiers (SKU, handle, etc.).
    """
    filters: search_filters.SearchFilters | None = None
    """
    Filter criteria to narrow returned products and variants. All specified filters combine with AND logic.
    """
    context: context_1.Context | None = None
    signals: signals_1.Signals | None = None
    attribution: attribution_1.Attribution | None = None


class Product(Product_1):
    model_config = ConfigDict(
        extra="allow",
    )
    variants: list[LookupVariant] | None = None


class GetProductRequest(BaseModel):
    """
    Request body for single-product retrieval. Supports interactive variant narrowing via selected and preferences.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Product or variant identifier. Implementations MUST support product ID and variant ID.
    """
    selected: list[selected_option.SelectedOption] | None = None
    """
    Partial or full option selections for interactive variant narrowing. When provided, response option values include availability signals (available, exists) relative to these selections.
    """
    preferences: list[str] | None = None
    """
    Option names in relaxation priority order. When no exact variant matches all selections, the server drops options from the end of this list first. E.g., ['Color', 'Size'] keeps Color and relaxes Size.
    """
    filters: search_filters.SearchFilters | None = None
    """
    Filter criteria to narrow returned variants. All specified filters combine with AND logic.
    """
    context: context_1.Context | None = None
    signals: signals_1.Signals | None = None
    attribution: attribution_1.Attribution | None = None


class Option(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    values: list[detail_option_value.DetailOptionValue] = Field(
        ..., min_length=1
    )


class DetailProduct(Product_1):
    """
    A product in a get_product response, extended with effective selections and availability signals on option values.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    selected: list[selected_option.SelectedOption] | None = None
    """
    Effective option selections that anchor the featured variant and availability signals. Required when the product has configurable options; may be empty or omitted for products with no option axes.
    """
    options: list[Option] | None = None
    """
    Product options with availability signals relative to the effective selections.
    """


class LookupResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.ResponseCatalogSchema
    products: list[Product]
    """
    Products matching the requested identifiers. May contain fewer items if some identifiers not found, or more if identifiers match multiple products.
    """
    messages: list[message.Message] | None = None
    """
    Errors, warnings, or informational messages about the requested items.
    """


class GetProductResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.ResponseCatalogSchema
    product: DetailProduct
    """
    The requested product with full detail. Singular — this is a single-resource operation.
    """
    messages: list[message.Message] | None = None
    """
    Warnings or informational messages about the product (e.g., price recently changed, limited availability).
    """
