# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict

from .. import ucp_update_request
from .types import (
    adjustment_update_request,
    expectation_update_request,
    fulfillment_event_update_request,
    message_update_request,
    order_line_item_update_request,
    totals_update_request,
)


class PlatformSchema(BaseModel):
    """
    Platform's order capability configuration.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    webhook_url: AnyUrl
    """
    URL where merchant sends order lifecycle events (webhooks).
    """


class Fulfillment(BaseModel):
    """
    Fulfillment data: buyer expectations and what actually happened.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    expectations: (
        list[expectation_update_request.ExpectationUpdateRequest] | None
    ) = None
    """
    Buyer-facing groups representing when/how items will be delivered. Can be split, merged, or adjusted post-order.
    """
    events: (
        list[fulfillment_event_update_request.FulfillmentEventUpdateRequest]
        | None
    ) = None
    """
    Append-only event log of actual shipments. Each event references line items by ID.
    """


class OrderUpdateRequest(BaseModel):
    """
    Order schema with line items, buyer-facing fulfillment expectations, and event logs.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_update_request.UcpMetadataUpdateRequest
    id: str
    """
    Unique order identifier.
    """
    label: str | None = None
    """
    Human-readable label for identifying the order. MUST only be provided by the business.
    """
    checkout_id: str
    """
    Associated checkout ID for reconciliation.
    """
    permalink_url: AnyUrl
    """
    Permalink to access the order on merchant site.
    """
    line_items: list[order_line_item_update_request.OrderLineItemUpdateRequest]
    """
    Line items representing what was purchased — can change post-order via edits or exchanges.
    """
    fulfillment: Fulfillment
    """
    Fulfillment data: buyer expectations and what actually happened.
    """
    adjustments: (
        list[adjustment_update_request.AdjustmentUpdateRequest] | None
    ) = None
    """
    Post-order events (refunds, returns, credits, disputes, cancellations, etc.) that exist independently of fulfillment.
    """
    totals: totals_update_request.TotalsUpdateRequest
    """
    Different totals for the order.
    """
    messages: list[message_update_request.MessageUpdateRequest] | None = None
    """
    Business outcome messages (errors, warnings, informational). Present when the business needs to communicate status or issues to the platform.
    """
