# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Category(BaseModel):
    """
    A product category with optional taxonomy identifier.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    value: str
    """
    Category value or path (e.g., 'Apparel > Shirts', '1604').
    """
    taxonomy: str | None = None
    """
    Source taxonomy. Well-known values: `google_product_category`, `shopify`, `merchant`.
    """
