# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict, Field

from ... import ucp as ucp_1
from . import message


class ErrorResponse(BaseModel):
    """
    Generic error response when business logic prevents resource creation or failed to retrieve resource. Used when no valid resource can be established.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.UcpMetadata
    """
    UCP protocol metadata. Status MUST be 'error' for error response.
    """
    messages: list[message.Message] = Field(..., min_length=1)
    """
    Array of messages describing why the operation failed.
    """
    continue_url: AnyUrl | None = None
    """
    URL for buyer handoff or session recovery.
    """
