# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Pagination(BaseModel):
    """
    Cursor-based pagination for list operations.
    """

    model_config = ConfigDict(
        extra="allow",
    )


class Request(BaseModel):
    """
    Pagination parameters for requests.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    cursor: str | None = None
    """
    Opaque cursor from previous response.
    """
    limit: int | None = Field(10, ge=1)
    """
    Requested page size. Implementations MAY clamp to a lower maximum.
    """


class Response(BaseModel):
    """
    Pagination information in responses.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    cursor: str | None = None
    """
    Cursor to fetch the next page of results. MUST be present when has_next_page is true.
    """
    has_next_page: bool
    """
    Whether more results are available.
    """
    total_count: int | None = Field(None, ge=0)
    """
    Total number of matching items, if available.
    """
