# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import amount as amount_1


class Price(BaseModel):
    """
    Price with explicit currency.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    amount: amount_1.Amount
    """
    Amount in ISO 4217 minor units. Use 0 for free items.
    """
    currency: str = Field(..., pattern="^[A-Z]{3}$")
    """
    ISO 4217 currency code (e.g., 'USD', 'EUR', 'GBP').
    """
