# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field

from . import category
from . import description as description_1
from . import media as media_1
from . import price_range as price_range_1
from . import product_option
from . import rating as rating_1
from . import variant


class Product(BaseModel):
    """
    A product in the catalog with variants and options.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Global ID (GID) uniquely identifying this product.
    """
    handle: str | None = None
    """
    URL-safe slug for SEO-friendly URLs (e.g., 'blue-runner-pro'). Use id for stable API references.
    """
    title: str
    """
    Product title.
    """
    description: description_1.Description
    """
    Product description in one or more formats.
    """
    url: AnyUrl | None = None
    """
    Canonical product page URL.
    """
    categories: list[category.Category] | None = None
    """
    Product categories with optional taxonomy identifiers.
    """
    price_range: price_range_1.PriceRange
    """
    Price range across all variants.
    """
    list_price_range: price_range_1.PriceRange | None = None
    """
    List price range before discounts (for strikethrough display).
    """
    media: list[media_1.Media] | None = None
    """
    Product media (images, videos, 3D models). First item is the featured media for listings.
    """
    options: list[product_option.ProductOption] | None = None
    """
    Product options (Size, Color, etc.).
    """
    variants: list[variant.Variant] = Field(..., min_length=1)
    """
    Purchasable variants of this product. First item is the featured variant for listings.
    """
    rating: rating_1.Rating | None = None
    """
    Aggregate product rating.
    """
    tags: list[str] | None = None
    """
    Product tags for categorization and search.
    """
    metadata: dict[str, Any] | None = None
    """
    Business-defined custom data extending the standard product model.
    """
