# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Rating(BaseModel):
    """
    Product rating aggregate.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    value: float = Field(..., ge=0.0)
    """
    Average rating value.
    """
    scale_min: float | None = Field(1, ge=0.0)
    """
    Minimum value on the rating scale (e.g., 1 for 1-5 stars).
    """
    scale_max: float = Field(..., ge=1.0)
    """
    Maximum value on the rating scale (e.g., 5 for 5-star).
    """
    count: int | None = Field(None, ge=0)
    """
    Number of reviews contributing to the rating.
    """
