# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class SignalsCreateRequest(BaseModel):
    """
    Environment data provided by the platform to support authorization and abuse prevention. Values MUST NOT be buyer-asserted claims — platforms provide signals based on direct observation or independently verifiable third-party attestations. All signal keys MUST use reverse-domain naming to ensure provenance and prevent collisions when multiple extensions contribute to the shared namespace.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    dev_ucp_buyer_ip: str | None = Field(None, alias="dev.ucp.buyer_ip")
    """
    Client's IP address (IPv4 or IPv6).
    """
    dev_ucp_user_agent: str | None = Field(None, alias="dev.ucp.user_agent")
    """
    Client's HTTP User-Agent header or equivalent.
    """
