# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import signed_amount
from .total import Total


class Line(BaseModel):
    """
    Sub-line entry. Additional metadata MAY be included.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    display_text: str
    """
    Human-readable label for this sub-line.
    """
    amount: signed_amount.SignedAmount


class TotalsUpdateRequestItem(Total):
    model_config = ConfigDict(
        extra="allow",
    )
    lines: list[Line] | None = None
    """
    Optional itemized breakdown. The parent entry is always rendered; lines are supplementary. Sum of line amounts MUST equal the parent entry amount.
    """


class TotalsUpdateRequest1(BaseModel):
    """
    Pricing breakdown provided by the business. MUST contain exactly one subtotal and one total entry. Detail types (tax, fee, discount, fulfillment) may appear multiple times for itemization. Platforms MUST render all entries in order using display_text and amount.
    """

    model_config = ConfigDict(
        extra="allow",
    )


class TotalsUpdateRequest(
    RootModel[list[TotalsUpdateRequestItem] | TotalsUpdateRequest1]
):
    """
    Pricing breakdown provided by the business. MUST contain exactly one subtotal and one total entry. Detail types (tax, fee, discount, fulfillment) may appear multiple times for itemization. Platforms MUST render all entries in order using display_text and amount.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: list[TotalsUpdateRequestItem] | TotalsUpdateRequest1 = Field(
        ..., title="Totals Update Request"
    )
    """
    Pricing breakdown provided by the business. MUST contain exactly one subtotal and one total entry. Detail types (tax, fee, discount, fulfillment) may appear multiple times for itemization. Platforms MUST render all entries in order using display_text and amount.
    """
