# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field

from . import amount as amount_1
from . import category
from . import description as description_1
from . import link
from . import media as media_1
from . import price as price_1
from . import rating as rating_1
from . import selected_option


class Barcode(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    """
    Barcode standard. Well-known values: UPC, EAN, ISBN, GTIN, JAN.
    """
    value: str
    """
    Barcode value.
    """


class Measure(BaseModel):
    """
    Product quantity in packaging (e.g., 750ml bottle).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    value: float
    """
    Package quantity.
    """
    unit: str
    """
    Unit of measurement.
    """


class Reference(BaseModel):
    """
    Denominator for unit price display (e.g., per 100ml, per 1kg).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    value: int
    """
    Reference quantity.
    """
    unit: str
    """
    Unit of measurement.
    """


class UnitPrice(BaseModel):
    """
    Price per standard unit of measurement. MAY be omitted when unit pricing does not apply.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    amount: amount_1.Amount
    """
    Unit price in ISO 4217 minor units. Business MUST return precomputed unit price value: (variant.price / measure.value) * reference.value.
    """
    currency: str = Field(..., pattern="^[A-Z]{3}$")
    """
    ISO 4217 currency code.
    """
    measure: Measure
    """
    Product quantity in packaging (e.g., 750ml bottle).
    """
    reference: Reference
    """
    Denominator for unit price display (e.g., per 100ml, per 1kg).
    """


class Availability(BaseModel):
    """
    Variant availability for purchase.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    available: bool | None = None
    """
    Whether this variant can be purchased. See status for fulfillment details.
    """
    status: str | None = None
    """
    Qualifies available with fulfillment state. Well-known values: `in_stock`, `backorder`, `preorder`, `out_of_stock`, `discontinued`.
    """


class Seller(BaseModel):
    """
    Optional seller context for this variant.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None
    """
    Seller display name.
    """
    links: list[link.Link] | None = None
    """
    Seller policy and information links.
    """


class Variant(BaseModel):
    """
    A purchasable variant of a product with specific option selections.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Global ID (GID) uniquely identifying this variant. Used as item.id in checkout.
    """
    sku: str | None = None
    """
    Business-assigned identifier for inventory and fulfillment.
    """
    barcodes: list[Barcode] | None = None
    """
    Industry-standard product identifiers for cross-reference and correlation.
    """
    handle: str | None = None
    """
    URL-safe variant handle/slug.
    """
    title: str
    """
    Variant display title (e.g., 'Blue / Large').
    """
    description: description_1.Description
    """
    Variant description in one or more formats.
    """
    url: AnyUrl | None = None
    """
    Canonical variant page URL.
    """
    categories: list[category.Category] | None = None
    """
    Variant categories with optional taxonomy identifiers.
    """
    price: price_1.Price
    """
    Current selling price.
    """
    list_price: price_1.Price | None = None
    """
    List price before discounts (for strikethrough display).
    """
    unit_price: UnitPrice | None = None
    """
    Price per standard unit of measurement. MAY be omitted when unit pricing does not apply.
    """
    availability: Availability | None = None
    """
    Variant availability for purchase.
    """
    options: list[selected_option.SelectedOption] | None = None
    """
    Option values that define this variant (e.g., Color: Blue, Size: Large).
    """
    media: list[media_1.Media] | None = None
    """
    Variant media (images, videos, 3D models). First item is the featured media for listings.
    """
    rating: rating_1.Rating | None = None
    """
    Variant rating.
    """
    tags: list[str] | None = None
    """
    Variant tags for categorization and search.
    """
    metadata: dict[str, Any] | None = None
    """
    Business-defined custom data extending the standard variant model.
    """
    seller: Seller | None = None
    """
    Optional seller context for this variant.
    """
