# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class UcpCapability(RootModel[Any]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Any = Field(..., title="UCP Capability")
    """
    Schema for UCP capabilities and extensions. Extensions are capabilities with an 'extends' field. Uses reverse-domain naming for governance.
    """


class Extends(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class Extends1Item(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")


class Extends1(RootModel[list[Extends1Item]]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: list[Extends1Item] = Field(..., min_length=1)
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class Extends2(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class Extends3Item(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")


class Extends3(RootModel[list[Extends3Item]]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: list[Extends3Item] = Field(..., min_length=1)
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class Extends4(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class Extends5Item(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")


class Extends5(RootModel[list[Extends5Item]]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: list[Extends5Item] = Field(..., min_length=1)
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class Extends6(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class Extends7Item(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")


class Extends7(RootModel[list[Extends7Item]]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: list[Extends7Item] = Field(..., min_length=1)
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class Version(RootModel[Any]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Any


class Base(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends | Extends1 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class PlatformSchema(BaseModel):
    """
    Full capability declaration for platform-level discovery. Includes spec/schema URLs for agent fetching.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl = Field(..., alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends2 | Extends3 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class BusinessSchema(BaseModel):
    """
    Capability configuration for business/merchant level. May include business-specific config overrides.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends4 | Extends5 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class ResponseSchema(BaseModel):
    """
    Capability reference in responses. Only name/version required to confirm active capabilities.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends6 | Extends7 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """
