# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel

from . import capability, payment_handler, service
from .shopping.types import reverse_domain_name


class Version(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(..., pattern="^\\d{4}-\\d{2}-\\d{2}$")
    """
    UCP version in YYYY-MM-DD format.
    """


class VersionConstraint(BaseModel):
    """
    Version range requirement with minimum and optional maximum.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    min: Version
    """
    Minimum required version (inclusive).
    """
    max: Version | None = None
    """
    Maximum compatible version (inclusive). When absent, no upper bound.
    """


class Requires(BaseModel):
    """
    Version requirements for extension schemas. Declares minimum (and optionally maximum) protocol and capability versions needed for correct operation.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    protocol: VersionConstraint | None = None
    """
    Required protocol version.
    """
    capabilities: (
        dict[reverse_domain_name.ReverseDomainName, VersionConstraint] | None
    ) = None
    """
    Required capability versions, keyed by capability name. Keys must be a subset of the extension's $defs keys.
    """


class Entity(BaseModel):
    """
    Shared foundation for all UCP entities.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """


class Base(BaseModel):
    """
    Base UCP metadata with shared properties for all schema types.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    status: Literal["success", "error"] | None = "success"
    """
    Application-level status of the UCP operation.
    """
    services: (
        dict[reverse_domain_name.ReverseDomainName, list[service.Base]] | None
    ) = None
    """
    Service registry keyed by reverse-domain name.
    """
    capabilities: (
        dict[reverse_domain_name.ReverseDomainName, list[capability.Base]]
        | None
    ) = None
    """
    Capability registry keyed by reverse-domain name.
    """
    payment_handlers: (
        dict[reverse_domain_name.ReverseDomainName, list[payment_handler.Base]]
        | None
    ) = None
    """
    Payment handler registry keyed by reverse-domain name.
    """


class Success(Base):
    """
    UCP metadata with status 'success'. Use for response branches that carry the expected payload.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    status: Literal["success"]
    """
    Application-level status of the UCP operation.
    """


class Error(Base):
    """
    UCP metadata with status 'error'. Use for response branches that carry error information.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    status: Literal["error"]
    """
    Application-level status of the UCP operation.
    """


class PlatformSchema(Base):
    """
    Full UCP metadata for platform-level configuration. Hosted at a URI advertised by the platform in request headers.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    services: dict[
        reverse_domain_name.ReverseDomainName, list[service.PlatformSchema5]
    ]
    """
    Service registry keyed by reverse-domain name.
    """
    capabilities: (
        dict[
            reverse_domain_name.ReverseDomainName,
            list[capability.PlatformSchema],
        ]
        | None
    ) = None
    """
    Capability registry keyed by reverse-domain name.
    """
    payment_handlers: dict[
        reverse_domain_name.ReverseDomainName,
        list[payment_handler.PlatformSchema],
    ]
    """
    Payment handler registry keyed by reverse-domain name.
    """


class BusinessSchema(Base):
    """
    UCP metadata for business/merchant-level configuration. Subset of platform schema with business-specific settings.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    supported_versions: dict[Version, AnyUrl] | None = None
    """
    Previous protocol versions this business supports, mapped to profile URIs. Businesses that support older protocol versions SHOULD advertise each version and link to its profile. Each URI points to a complete, self-contained profile for that version. When omitted, only `version` is supported.
    """
    services: dict[
        reverse_domain_name.ReverseDomainName, list[service.BusinessSchema2]
    ]
    """
    Service registry keyed by reverse-domain name.
    """
    capabilities: (
        dict[
            reverse_domain_name.ReverseDomainName,
            list[capability.BusinessSchema],
        ]
        | None
    ) = None
    """
    Capability registry keyed by reverse-domain name.
    """
    payment_handlers: dict[
        reverse_domain_name.ReverseDomainName,
        list[payment_handler.BusinessSchema],
    ]
    """
    Payment handler registry keyed by reverse-domain name.
    """


class ResponseCheckoutSchema(Base):
    """
    UCP metadata for checkout responses.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    services: (
        dict[
            reverse_domain_name.ReverseDomainName, list[service.ResponseSchema2]
        ]
        | None
    ) = None
    """
    Service registry keyed by reverse-domain name.
    """
    capabilities: (
        dict[
            reverse_domain_name.ReverseDomainName,
            list[capability.ResponseSchema],
        ]
        | None
    ) = None
    """
    Capability registry keyed by reverse-domain name.
    """
    payment_handlers: dict[
        reverse_domain_name.ReverseDomainName,
        list[payment_handler.ResponseSchema],
    ]
    """
    Payment handler registry keyed by reverse-domain name.
    """


class ResponseOrderSchema(Base):
    """
    UCP metadata for order responses. No payment handlers needed post-purchase.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    capabilities: (
        dict[
            reverse_domain_name.ReverseDomainName,
            list[capability.ResponseSchema],
        ]
        | None
    ) = None
    """
    Capability registry keyed by reverse-domain name.
    """


class ResponseCartSchema(Base):
    """
    UCP metadata for cart responses. No payment handlers needed pre-checkout.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    capabilities: (
        dict[
            reverse_domain_name.ReverseDomainName,
            list[capability.ResponseSchema],
        ]
        | None
    ) = None
    """
    Capability registry keyed by reverse-domain name.
    """


class ResponseCatalogSchema(Base):
    """
    UCP metadata for catalog responses.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    capabilities: (
        dict[
            reverse_domain_name.ReverseDomainName,
            list[capability.ResponseSchema],
        ]
        | None
    ) = None
    """
    Capability registry keyed by reverse-domain name.
    """


class UcpMetadata(
    RootModel[
        PlatformSchema
        | BusinessSchema
        | ResponseCheckoutSchema
        | ResponseOrderSchema
        | ResponseCartSchema
    ]
):
    model_config = ConfigDict(
        frozen=True,
    )
    root: (
        PlatformSchema
        | BusinessSchema
        | ResponseCheckoutSchema
        | ResponseOrderSchema
        | ResponseCartSchema
    ) = Field(..., title="UCP Metadata")
    """
    Protocol metadata for discovery profiles and responses. Uses slim schema pattern with context-specific required fields.
    """
